from selenium import webdriver
from selenium.webdriver.common.by import By
import pyautogui
import csv 
import time;
import requests
import threading
import os


def save_text_to_text_file(text, file_path):
    with open(file_path, 'a', encoding='utf-8') as file: 
        file.write(text + '\n')

urls = [

'https://fbcci.org/web/profile/sk-liakat-hossain',
'https://fbcci.org/web/profile/mrs-hasina-newaaz',
'https://fbcci.org/web/profile/mr-sardar-omar-faruk',
'https://fbcci.org/web/profile/mr-madhu-sudan-dam1',
'https://fbcci.org/web/profile/mr-krishna-das1',
'https://fbcci.org/web/profile/khan-ali-ahmed-khokon',
'https://fbcci.org/web/profile/ms-lal-chhani-lushai',
'https://fbcci.org/web/profile/ms-urmi-chowdhury',
'https://fbcci.org/web/profile/ms-kamrun-nahar',
'https://fbcci.org/web/profile/kazi-zihan-zahan',
'https://fbcci.org/web/profile/mr-mohammad-masudul-islam',
'https://fbcci.org/web/profile/mr-anwar-ul--alam-chowdhury-parvez%0A-%0A-%0A',
'https://fbcci.org/web/profile/mr-emdadul-haque-mozumder',
'https://fbcci.org/web/profile/ms-anjum-sultana-sima,-mp',
'https://fbcci.org/web/profile/ms-syeda-afifa-akther',
'https://fbcci.org/web/profile/ms-saima-khan',
'https://fbcci.org/web/profile/ms-zinnathshakilayeasmin',
'https://fbcci.org/web/profile/mrs-nurjahan-akter',
'https://fbcci.org/web/profile/mrs-aparna-chakraborty',
'https://fbcci.org/web/profile/mr-md-sameer-sattar1',
'https://fbcci.org/web/profile/mr-rizwan--ur--rahman',
'https://fbcci.org/web/profile/ms-nasrin-sultana-lucky',
'https://fbcci.org/web/profile/mr-a-k-m-aftab-ul-islam-fca',
'https://fbcci.org/web/profile/mr-abul-kasem-khan',
'https://fbcci.org/web/profile/mr-asif-ibrahim',
'https://fbcci.org/web/profile/mr-shams-mahmud',
'https://fbcci.org/web/profile/ms-naaz-farhana-ahmed',
'https://fbcci.org/web/profile/ms-aneeka-agha',
'https://fbcci.org/web/profile/ms-bedowra-ahmed-salam',
'https://fbcci.org/web/profile/ms-sharif-sene-shembil',
'https://fbcci.org/web/profile/ms-sajeda-minhaj-mukul',
'https://fbcci.org/web/profile/mrs-fauzia-amin',
'https://fbcci.org/web/profile/mr-reza-humayun-faruque-chowdhury-shamim',
'https://fbcci.org/web/profile/mr-md-mosaddaque-hossain',
'https://fbcci.org/web/profile/mr-md-akhtaruzzaman-jewel',
'https://fbcci.org/web/profile/syed-sagir-ahmmed',
'https://fbcci.org/web/profile/mr-shahed-riaj-pim',
'https://fbcci.org/web/profile/mr-protap-kumar-saha',
'https://fbcci.org/web/profile/mir-nasir-hossain1',
'https://fbcci.org/web/profile/mr-shamim-haque',
'https://fbcci.org/web/profile/mr-md-nazrul-islam3',
'https://fbcci.org/web/profile/shah-md-istiaque-arif',
'https://fbcci.org/web/profile/mr-abdul-kader-azad1',
'https://fbcci.org/web/profile/mr-md-shamsul-alam-chowdhuri',
'https://fbcci.org/web/profile/mr-md-motiur-rahman-shamim',
'https://fbcci.org/web/profile/mr-aynul-kabir',
'https://fbcci.org/web/profile/mr-akm-shaheed-reza',
'https://fbcci.org/web/profile/mr-alauddin',
'https://fbcci.org/web/profile/mr-abul-kashem',
'https://fbcci.org/web/profile/mr-farid-uddin-ahamed-pathan',
'https://fbcci.org/web/profile/mr-mohammed-nur-azam',
'https://fbcci.org/web/profile/mr-naser-ezaz-bijoy',
'https://fbcci.org/web/profile/mrs-shwapna-bhowmick',
'https://fbcci.org/web/profile/mr-mohammad-ismail-hossain%0A',
'https://fbcci.org/web/profile/mr-zaved-akhtar',
'https://fbcci.org/web/profile/mr-abdur-rashid1',
'https://fbcci.org/web/profile/mr-yasir-azman',
'https://fbcci.org/web/profile/mr-jahangir-sadat',
'https://fbcci.org/web/profile/bir-mukti-juddha-md-moksuder-rahman-shahan',
'https://fbcci.org/web/profile/mr-md-abdur-rashid',
'https://fbcci.org/web/profile/khan-mohammad-said-hossin-jashim',
'https://fbcci.org/web/profile/mr-md-nawsher-alam',
'https://fbcci.org/web/profile/mr-md-mostak-ahmmed-ranju',
'https://fbcci.org/web/profile/mr-md-hasan-mahmud-jony',
'https://fbcci.org/web/profile/mr-md-shahidul-islam-niru',
'https://fbcci.org/web/profile/mohammad-anwar-sadat-sarker2',
'https://fbcci.org/web/profile/heaven-housing-corporation-14-poura-super-market-1st-floor-joydebpur-gazipur-1700',
'https://fbcci.org/web/profile/mr-md-motiur-rahman1',
'https://fbcci.org/web/profile/mr-md-mojibur-rahman1',
'https://fbcci.org/web/profile/mr-md-shakawat-hossain',
'https://fbcci.org/web/profile/mr-shahjahan-mondol',
'https://fbcci.org/web/profile/sheikh-fazle-fahim1',
'https://fbcci.org/web/profile/kazi-zinnat-ali',
'https://fbcci.org/web/profile/alhaj-md-mosharraf-hossain',
'https://fbcci.org/web/profile/sheikh-masudur-rahman',
'https://fbcci.org/web/profile/mr-delowar-hossain-raja',
'https://fbcci.org/web/profile/mr-ali-nayeem-khan',
'https://fbcci.org/web/profile/mr-sujib-ranjan-dash',
'https://fbcci.org/web/profile/md-rejaul-kariem-rejnu',
'https://fbcci.org/web/profile/mr-md-zakir-hossen',
'https://fbcci.org/web/profile/mr-ranjan-kumar-singh',
'https://fbcci.org/web/profile/mr-subir-basak',
'https://fbcci.org/web/profile/mr-md-mustafizur-rahman-bappy',
'https://fbcci.org/web/profile/mr-md-murshadul-alam-raju',
'https://fbcci.org/web/profile/alhaj-sarder-mohammad-shah-alam',
'https://fbcci.org/web/profile/mr-mahabub-hossain',
'https://fbcci.org/web/profile/mr-mahbub-hossain',
'https://fbcci.org/web/profile/mr-joshoda-jibon-debnath%0A%0A%0A',
'https://fbcci.org/web/profile/alhaj-salah-uddin-ahmed-salek',
'https://fbcci.org/web/profile/alhaj-ferdous-ahmed-titu',
'https://fbcci.org/web/profile/mr-md-ahsan-kabir-aplob%0A%0A',
'https://fbcci.org/web/profile/mr-md-belayet-hossain-labu%0A%0A',
'https://fbcci.org/web/profile/alhaj-md-liyaqut-ali-talukder',
'https://fbcci.org/web/profile/mr-sushil-kumar-mondal',
'https://fbcci.org/web/profile/mr-md-ehsanuzzaman-nazmul',
'https://fbcci.org/web/profile/mr-md-ainul-haque-russo',
'https://fbcci.org/web/profile/mr-omprakash-agarwala',
'https://fbcci.org/web/profile/mr-md-monirul-islam%0A%0A',
'https://fbcci.org/web/profile/ms-selima-ahmad,-mp%0A%0A',
'https://fbcci.org/web/profile/kazi-aminul-haque%0A%0A',
'https://fbcci.org/web/profile/kazi-masudul-islam',
'https://fbcci.org/web/profile/mr-md-abul-hasan',
'https://fbcci.org/web/profile/mr-md-islam-khan',
'https://fbcci.org/web/profile/khan-saiful-islam',
'https://fbcci.org/web/profile/chowdhury-minhaz-uz-zaman',
'https://fbcci.org/web/profile/mr-mohammad-muzibur-rahman-belal',
'https://fbcci.org/web/profile/sheikh-farid-ahammed',
'https://fbcci.org/web/profile/mr-gazi-golam-ashria',
'https://fbcci.org/web/profile/mr-khaliluz-zaman',
'https://fbcci.org/web/profile/ms-sangita-ahmed%0A%0A',
'https://fbcci.org/web/profile/sheak-ashadujzaman-khokon',
'https://fbcci.org/web/profile/mr-golam-dastagir-gazi,-mp',
'https://fbcci.org/web/profile/ms-fatema-zohra-akther',
'https://fbcci.org/web/profile/ms-esrat-jahan-mimi',
'https://fbcci.org/web/profile/ms-tania-akther',
'https://fbcci.org/web/profile/ms-nahid-taslima',
'https://fbcci.org/web/profile/ms-rahana-parvez',
'https://fbcci.org/web/profile/mr-farzana-akhter',
'https://fbcci.org/web/profile/mr-abdul-aziz-miah',
'https://fbcci.org/web/profile/mr-alak-sarker',
'https://fbcci.org/web/profile/ms-selina-quader%0A%0A',
'https://fbcci.org/web/profile/mr-md-nuruzzaman',
'https://fbcci.org/web/profile/mr-abu-md-sayed-hassan-loban',
'https://fbcci.org/web/profile/mr-mahamudun-nobi',
'https://fbcci.org/web/profile/mr-tabarakul-tosaddek-hossain-khan-tito',
'https://fbcci.org/web/profile/mr-md-mozibar-rahman',
'https://fbcci.org/web/profile/haji-md-robiul-islam',
'https://fbcci.org/web/profile/mr-md-nasir-uddin-mridha',
'https://fbcci.org/web/profile/mr-bijoy-kumar-kejriwal1',
'https://fbcci.org/web/profile/mr-shamsul-washe',
'https://fbcci.org/web/profile/mr-ma-khaleque',
'https://fbcci.org/web/profile/ms-farkhunda-jabeen-khan',
'https://fbcci.org/web/profile/al-haj-sheikh-abdul-hamid',
'https://fbcci.org/web/profile/mr-md-humaun-kabir',
'https://fbcci.org/web/profile/al-haj-shah-alom-shekh',
'https://fbcci.org/web/profile/al-haj-khorshed-ahmed-dulal',
'https://fbcci.org/web/profile/al-haj-md-shekender-ali',
'https://fbcci.org/web/profile/mr-md-shakawat-hossain1',
'https://fbcci.org/web/profile/mr-hafizur-rahman-khan',
'https://fbcci.org/web/profile/mr-babul-chandra-das',
'https://fbcci.org/web/profile/mr-sabbir-bhuiyanchoto',
'https://fbcci.org/web/profile/mr-monirul-islam-bhuya-moon',
'https://fbcci.org/web/profile/ms-priti-chakraborty',
'https://fbcci.org/web/profile/mir-habibur-rahman',
'https://fbcci.org/web/profile/mr-md-mizanur-rahman',
'https://fbcci.org/web/profile/mr-afsar-uddin-sarkar',
'https://fbcci.org/web/profile/mr-rahat-maleque',
'https://fbcci.org/web/profile/mr-sultanul-azam-khan',
'https://fbcci.org/web/profile/mr-sudeb-kumar-saha',
'https://fbcci.org/web/profile/mr-rafiqul-islam-paran',
'https://fbcci.org/web/profile/mrmd-abdul-zalil',
'https://fbcci.org/web/profile/mr-md-saiful-islam2',
'https://fbcci.org/web/profile/mr-habibullah-n-karim',
'https://fbcci.org/web/profile/ms-shahana-jefreen',
'https://fbcci.org/web/profile/ms-nihad-kabir1',
'https://fbcci.org/web/profile/mr-golam-mainuddin',
'https://fbcci.org/web/profile/mrs-uzma-chowdhury',
'https://fbcci.org/web/profile/mr-farooq-ahmed1',
'https://fbcci.org/web/profile/mr-md-kamal-hossain1',
'https://fbcci.org/web/profile/mr-mdabu-sufian',
'https://fbcci.org/web/profile/mr-md-khairuzzaman',
'https://fbcci.org/web/profile/syed-munim-ahmed-rimon',
'https://fbcci.org/web/profile/mr-md-suhad',
'https://fbcci.org/web/profile/mr-zafar-ahmed-gilman',
'https://fbcci.org/web/profile/serneabat-sadiq-abdullah-%0A',
'https://fbcci.org/web/profile/alhaj-nur-mohammad',
'https://fbcci.org/web/profile/mr-md-kohinoor-islam1',
'https://fbcci.org/web/profile/mrs-nazneen-hossain',
'https://fbcci.org/web/profile/mr-masud-kader-mona',
'https://fbcci.org/web/profile/mr-tazedul-islam',
'https://fbcci.org/web/profile/mr-md-shahidullah-khan',
'https://fbcci.org/web/profile/mr-md-aminul-hoque-shamim',
'https://fbcci.org/web/profile/mr-sankar-saha',
'https://fbcci.org/web/profile/mr-samiul-hoque-safa',
'https://fbcci.org/web/profile/mr-md-imran-omer',
'https://fbcci.org/web/profile/alhaj-saidur-rahaman-rintu%0A%0A',
'https://fbcci.org/web/profile/mr-s-m-bazlur-rahman',
'https://fbcci.org/web/profile/mr-pallab-saha',
'https://fbcci.org/web/profile/mrmd-iqbal-shahriar',
'https://fbcci.org/web/profile/mrmd-mostafizur-rahman',
'https://fbcci.org/web/profile/alhaz-abdul-khalek',
'https://fbcci.org/web/profile/mr-amiyo-kumar-das',
'https://fbcci.org/web/profile/mr-md-aminul-haque',
'https://fbcci.org/web/profile/mr-md-motahar-hossain',
'https://fbcci.org/web/profile/mr-md-khalid-haider-khan',
'https://fbcci.org/web/profile/mr-md-morshed-sarwar%0A%0A-%0A',
'https://fbcci.org/web/profile/serniabatmoyeenuddin-abdullah-',
'https://fbcci.org/web/profile/mr-md-shahadath-hossain-bhuyan',
'https://fbcci.org/web/profile/mr-prabir-kumar-saha',
'https://fbcci.org/web/profile/mr-imtinan-osman',
'https://fbcci.org/web/profile/mr-sohel-akhter',
'https://fbcci.org/web/profile/mr-mdali-hossain',
'https://fbcci.org/web/profile/mr-abdul-momen-molla',
'https://fbcci.org/web/profile/mr-mahmodul-hasan1',
'https://fbcci.org/web/profile/mr-md-anisur-rahman-bhuiyan',
'https://fbcci.org/web/profile/mr-md-kazim-uddin',
'https://fbcci.org/web/profile/mr-shahidul-islam2',
'https://fbcci.org/web/profile/mr-jahangir-hossain-manik',
'https://fbcci.org/web/profile/engr-sm-shofiqul-alam-dablu',
'https://fbcci.org/web/profile/mrs-afsana-afrose',
'https://fbcci.org/web/profile/mr-md-abid-hossain',
'https://fbcci.org/web/profile/mr-md-monirul-islam-sweden',
'https://fbcci.org/web/profile/mr-sujit-kumar-chakroborti',
'https://fbcci.org/web/profile/mr-md-hossain-khan-manik',
'https://fbcci.org/web/profile/mr-md-ataur-rahman-bhuiya1',
'https://fbcci.org/web/profile/mr-md-mahamudur-rahman',
'https://fbcci.org/web/profile/mr-abdul-wadud-pintu1',
'https://fbcci.org/web/profile/mr-golam-zilani-didar1',
'https://fbcci.org/web/profile/kazi-nazrul-islam',
'https://fbcci.org/web/profile/mr-shofiul-azam-pintu',
'https://fbcci.org/web/profile/mr-akm-shamsuddin-zahan',
'https://fbcci.org/web/profile/mr-md-saiful-alom-swapan-choudhury',
'https://fbcci.org/web/profile/mr-ali-mortoja-biswas',
'https://fbcci.org/web/profile/mr-md-forkan-reja-biswas',
'https://fbcci.org/web/profile/mr-shafiqul-islam-khan',
'https://fbcci.org/web/profile/mr-md-ruhul-amin-biswas-rana',
'https://fbcci.org/web/profile/mr-masudur-rahman-mintu',
'https://fbcci.org/web/profile/alhaj-md-abdul-hannan-sheikh',
'https://fbcci.org/web/profile/mr-md-rezaul-karim-reza',
'https://fbcci.org/web/profile/mr-ma-awal-chowdhury',
'https://fbcci.org/web/profile/mr-md-khazim-uddin',
'https://fbcci.org/web/profile/alhaj-md-sharif-hossain',
'https://fbcci.org/web/profile/mr-a-t-m-kamruzzaman-shahansha',
'https://fbcci.org/web/profile/mr-md-abdus-sabur-selim',
'https://fbcci.org/web/profile/mr-md-gius-uddin',
'https://fbcci.org/web/profile/kazi-alomgir',
'https://fbcci.org/web/profile/mr-md-mizanur-rahman-monir',
'https://fbcci.org/web/profile/mr-mohiuddin-ahmed',
'https://fbcci.org/web/profile/mr-gm-jafar',
'https://fbcci.org/web/profile/mr-gm-jafor',
'https://fbcci.org/web/profile/mr-md-nizam-uddin',
'https://fbcci.org/web/profile/ms-ismat-jerin-khan',
'https://fbcci.org/web/profile/ms-nurun-nahar-khan',
'https://fbcci.org/web/profile/ms-shulka-roy',
'https://fbcci.org/web/profile/ms-laizu-akter',
'https://fbcci.org/web/profile/ms-rubina-akter-munni',
'https://fbcci.org/web/profile/ms-reba-rani-hawlader',
'https://fbcci.org/web/profile/mr-md-shamsuzzaman',
'https://fbcci.org/web/profile/mr-masudur-rahman-rinku',
'https://fbcci.org/web/profile/mr-md-shahadat-hossian',
'https://fbcci.org/web/profile/mr-tured-al-masud',
'https://fbcci.org/web/profile/mr-abdul-matlub-ahmad%0A',
'https://fbcci.org/web/profile/mr-abm-habibullha-dollar',
'https://fbcci.org/web/profile/mr-md-harun-ur-rashid',
'https://fbcci.org/web/profile/ms-rosettee-najneen',
'https://fbcci.org/web/profile/mst-tahera-hasen',
'https://fbcci.org/web/profile/mst-biddut-ara-mame',
'https://fbcci.org/web/profile/mst-rakhi-begum',
'https://fbcci.org/web/profile/mst-deloara-begum',
'https://fbcci.org/web/profile/ms-musharrat-jahan',
'https://fbcci.org/web/profile/mr-md-abdul-wadud',
'https://fbcci.org/web/profile/mr-monsur-ali',
'https://fbcci.org/web/profile/mr-razin-ul-kabir',
'https://fbcci.org/web/profile/mohammed-bazlur-rahman',
'https://fbcci.org/web/profile/mr-md-nizam-uddin2',
'https://fbcci.org/web/profile/mr-md-moniruzzaman-mohsin',
'https://fbcci.org/web/profile/mr-abul-mansur-obaidullah',
'https://fbcci.org/web/profile/mr-mostofa-sohrab-chowdhury-titu',
'https://fbcci.org/web/profile/mr-mostofa-azad-chowdhury-babu',
'https://fbcci.org/web/profile/mr-md-shahjahan-babu',
'https://fbcci.org/web/profile/mr-md-akbar-ali',
'https://fbcci.org/web/profile/mr-abu-hena-md-rezwanul-karim',
'https://fbcci.org/web/profile/mr-md-javed-hasan',
'https://fbcci.org/web/profile/mr-md-humayun-kabir1',
'https://fbcci.org/web/profile/mr-md-rezaul-islam-milon',
'https://fbcci.org/web/profile/mr-md-ghulam-zakaria',
'https://fbcci.org/web/profile/mr-md-atik-ullah',
'https://fbcci.org/web/profile/mr-salahuddin-mostofa-jamal',
'https://fbcci.org/web/profile/syed-shah-newaz-ali',
'https://fbcci.org/web/profile/mr-md-rubayet-hossain-khan',
'https://fbcci.org/web/profile/mrs-anowara-ferdousi-poly',
'https://fbcci.org/web/profile/ms-akter-jahan-arshi',
'https://fbcci.org/web/profile/mrs-roksana-rahman',
'https://fbcci.org/web/profile/mrs-mostary-morshed',
'https://fbcci.org/web/profile/mr-md-zakir-hossain-azad-',
'https://fbcci.org/web/profile/mrs-jannatul-ferdus',
'https://fbcci.org/web/profile/mrs-barna',
'https://fbcci.org/web/profile/mr-nasim-faruk-khan-mithu',
'https://fbcci.org/web/profile/mr-ansan-bahar-bulbul',
'https://fbcci.org/web/profile/mr-sheikh-kamruzzaman',
'https://fbcci.org/web/profile/syed-sahinur-ali',
'https://fbcci.org/web/profile/mr-md-moshiur-rahman',
'https://fbcci.org/web/profile/mr-fakhorus-salehin-nahiyan',
'https://fbcci.org/web/profile/mr-akm-ismail-haq',
'https://fbcci.org/web/profile/mr-abdus-salam-bapari',
'https://fbcci.org/web/profile/mr-sa-wadud',
'https://fbcci.org/web/profile/alhaj-md-mozibar-rahman-khan',
'https://fbcci.org/web/profile/mr-md-ruhul-amin-manik',
'https://fbcci.org/web/profile/mr-md-abul-hashem-molla',
'https://fbcci.org/web/profile/mr-imran-bepary',
'https://fbcci.org/web/profile/alhaj-asaduzzaman-roushan',
'https://fbcci.org/web/profile/mr-prokash-datta',
'https://fbcci.org/web/profile/alhaj-md-arif-hossain',
'https://fbcci.org/web/profile/heroic-freedom-fighter-md-masud',
'https://fbcci.org/web/profile/mr-gopal-chandra-saha',
'https://fbcci.org/web/profile/mr-salah-uddin-ali-ahmed',
'https://fbcci.org/web/profile/mr-md-ariful-kabir-apal',
'https://fbcci.org/web/profile/mrs-bilkis-ahmed',
'https://fbcci.org/web/profile/ms-monijamasud',
'https://fbcci.org/web/profile/ms-shahina-akhter-parvin',
'https://fbcci.org/web/profile/ms-nasrin-begum-fatema1',
'https://fbcci.org/web/profile/ms-shamsunnahar-kamal',
'https://fbcci.org/web/profile/ms-shamshad-jahan-laizu',
'https://fbcci.org/web/profile/ms-irin-parvin',
'https://fbcci.org/web/profile/mr-md-golam-abu-yousuf-surju',
'https://fbcci.org/web/profile/syed-abdurrouf-mukta',
'https://fbcci.org/web/profile/mr-mohammed-riyadh-ali',
'https://fbcci.org/web/profile/mr-ishaka-ali',
'https://fbcci.org/web/profile/ms-samema-nizam',
'https://fbcci.org/web/profile/mr-kamrul-hasan-hilton',
'https://fbcci.org/web/profile/mr-md-amdadul-haque',
'https://fbcci.org/web/profile/ms-sharita-millat',
'https://fbcci.org/web/profile/ms-begum-farida-reaz',
'https://fbcci.org/web/profile/mst-rumana-rasma',
'https://fbcci.org/web/profile/ms-most-mukta-khatun',
'https://fbcci.org/web/profile/most-zannatul-ferdaus',
'https://fbcci.org/web/profile/mr-amatun-noor%0A',
'https://fbcci.org/web/profile/mr-khairul-huda-chopol',
'https://fbcci.org/web/profile/mr-md-anamul-haque',
'https://fbcci.org/web/profile/mr-kashfiqur-rahman',
'https://fbcci.org/web/profile/mr-amal-kanti-kar',
'https://fbcci.org/web/profile/mr-ahmed-shakhawat-selim-chowdhury',
'https://fbcci.org/web/profile/mr-md-noorealam',
'https://fbcci.org/web/profile/mr-kamrul-huda-sochi',
'https://fbcci.org/web/profile/ms-husna-huda',
'https://fbcci.org/web/profile/ms-rimina-ankther',
'https://fbcci.org/web/profile/ms-farhanaz-fatima-reya',
'https://fbcci.org/web/profile/ms-nasrin-sultana-dipa',
'https://fbcci.org/web/profile/ms-sayeda-farhana-ima',
'https://fbcci.org/web/profile/ms-tazrin-chowdhury',
'https://fbcci.org/web/profile/mrs-nasima-akhter',
'https://fbcci.org/web/profile/mr-md-hizkil-gulzar%0A-%0A-%0A-%0A',
'https://fbcci.org/web/profile/mr-mushfiquejaigirdar',
'https://fbcci.org/web/profile/mr-wahiduzzaman-chowdhury-rajib',
'https://fbcci.org/web/profile/mr-fahim-ahmed-chowdhury',
'https://fbcci.org/web/profile/mr-debangshu-das',
'https://fbcci.org/web/profile/mr-afzal-rashid-chowdhury',
'https://fbcci.org/web/profile/mr-md-abdul-jabbir-jalil',
'https://fbcci.org/web/profile/mr-shafiul-alam-chowdhury',
'https://fbcci.org/web/profile/mr-tahmin-ahmed',
'https://fbcci.org/web/profile/ms-monowara-begum',
'https://fbcci.org/web/profile/mr-md-huraira-iftar-hussain',
'https://fbcci.org/web/profile/mr-md-rezaul-hasan-jakaria',
'https://fbcci.org/web/profile/ms-sharnalata-roy',
'https://fbcci.org/web/profile/sayeda-rabeya-akhter-ria',
'https://fbcci.org/web/profile/ms-lubana-yesmin',
'https://fbcci.org/web/profile/ms-tasmine-akther',
'https://fbcci.org/web/profile/ms-beauty-barmon',
'https://fbcci.org/web/profile/ms-sheuli-begum',
'https://fbcci.org/web/profile/khan-ahmed-shovo',
'https://fbcci.org/web/profile/mr-md-sanowar-hossain-mp',
'https://fbcci.org/web/profile/ms-taufiqun-nessa-lucky',
'https://fbcci.org/web/profile/mr-soto-monir-mp',
'https://fbcci.org/web/profile/khandakar-tarikul-islam-tareq',
'https://fbcci.org/web/profile/mr-saifuzzaman-sohel',
'https://fbcci.org/web/profile/mr-md-jamilur-rahman',
'https://fbcci.org/web/profile/mr-kyaw-shwe-hla-marma',
'https://fbcci.org/web/profile/mr-laxmi-pada-das',
'https://fbcci.org/web/profile/mr-amal-kanti-das1',
'https://fbcci.org/web/profile/mr-akm-jahangir',
'https://fbcci.org/web/profile/alhaj-md-jahangir-kabir',
'https://fbcci.org/web/profile/alhaj-md-zahirul-haque-panu',
'https://fbcci.org/web/profile/mr-md-abdul-mamintulu',
'https://fbcci.org/web/profile/mr-dilip-karmokar',
'https://fbcci.org/web/profile/mr-kabirur-rahman',
'https://fbcci.org/web/profile/mr-md-humayun-kabir-1',
'https://fbcci.org/web/profile/mr-mousharrof-hossain',
'https://fbcci.org/web/profile/mr-muhammad-zahidul-haque',
'https://fbcci.org/web/profile/mr-mohammad-fayazur-rahmanbhuiyan',
'https://fbcci.org/web/profile/mohammad-fayazur-rahman-bhuiyan%0A',
'https://fbcci.org/web/profile/mr-md-kashem',
'https://fbcci.org/web/profile/mr-abu-morshed-chowdhury',
'https://fbcci.org/web/profile/mr-shahidul-kader-chowdhury',
'https://fbcci.org/web/profile/mr-mohammed-anwarul-islam',
'https://fbcci.org/web/profile/mr-abed-ahasan-sagar',
'https://fbcci.org/web/profile/mr-md-maniruzzaman',
'https://fbcci.org/web/profile/mr-md-mizanur-rahman-shamim',
'https://fbcci.org/web/profile/mr-abu-henamostofa-kamal',
'https://fbcci.org/web/profile/mr-abdur-rahman1',
'https://fbcci.org/web/profile/sheikh-anisuzzaman',
'https://fbcci.org/web/profile/mr-kongjari-chowdhury',
'https://fbcci.org/web/profile/mr-sm-jahangir-alam-manik',
'https://fbcci.org/web/profile/mr-mddidarulalam',
'https://fbcci.org/web/profile/mr-akm-shajahan-kamal,-mp',
'https://fbcci.org/web/profile/mr-dewan-sultan-ahmed',
'https://fbcci.org/web/profile/mr-md-nazrul-islam-golder',
'https://fbcci.org/web/profile/mr-mohabbat-ullah',
'https://fbcci.org/web/profile/mr-shankar-majumder',
'https://fbcci.org/web/profile/mr-md-nazmul-haque',
'https://fbcci.org/web/profile/mr-md-anisur-rahman',
'https://fbcci.org/web/profile/mr-md-muzahidul-islam-nantu',
'https://fbcci.org/web/profile/haji-md-golam-rosul',
'https://fbcci.org/web/profile/mr-arifulanam-bokul',
'https://fbcci.org/web/profile/mr-ma-razzak-khan',
'https://fbcci.org/web/profile/mr-md-aslam-khan',
'https://fbcci.org/web/profile/mr-md-shafiqul-islam',
'https://fbcci.org/web/profile/mr-mdhazanuzzaman',
'https://fbcci.org/web/profile/syed-ahsan-kabir',
'https://fbcci.org/web/profile/mr-md-badrul-alam',
'https://fbcci.org/web/profile/alhaz-md-woahiduzzaman',
'https://fbcci.org/web/profile/mr-md-shoriful-islam-romzan',
'https://fbcci.org/web/profile/mr-shyam-sunder-agarwala',
'https://fbcci.org/web/profile/mr-md-abdul-mannaf',
'https://fbcci.org/web/profile/mr-sujit-kumar-sarkar',
'https://fbcci.org/web/profile/mr-md-ashraf-ali-khan-khasru',
'https://fbcci.org/web/profile/mr-manu-mazumder',
'https://fbcci.org/web/profile/mr-md-zahirul-islam-nakib',
'https://fbcci.org/web/profile/mr-abdul-wahed',
'https://fbcci.org/web/profile/jasmin-rahman-shilpe',
'https://fbcci.org/web/profile/dr-sm-mizanur-rahman',
'https://fbcci.org/web/profile/khalekuzzaman-khokon',
'https://fbcci.org/web/profile/kazi-eradat-ali1',
'https://fbcci.org/web/profile/mr-md-zakir-hossain',
'https://fbcci.org/web/profile/md-nazibar-rahman',
'https://fbcci.org/web/profile/kazirakibul-hossain-shantonu',
'https://fbcci.org/web/profile/mr-mainul-hossain',
'https://fbcci.org/web/profile/mr-md-masudur-rahman-milon',
'https://fbcci.org/web/profile/mr-md-abul-kalam-azad2',
'https://fbcci.org/web/profile/mr-t-m-ali-haider',
'https://fbcci.org/web/profile/mr-md-golam-kibria-bahar',
'https://fbcci.org/web/profile/mr-ashok-roy',
'https://fbcci.org/web/profile/mr-md-parvej-hossen-uzzal',
'https://fbcci.org/web/profile/alhaj-azizul-hoque',
'https://fbcci.org/web/profile/kazi-jahangir',
'https://fbcci.org/web/profile/mr-azizur-rahman-shamim',
'https://fbcci.org/web/profile/mr-subrata-paul',
'https://fbcci.org/web/profile/mrtanvirahmed',
'https://fbcci.org/web/profile/mr-md-al-mamun',
'https://fbcci.org/web/profile/mr-md-jahangir-akhand-salim1',
'https://fbcci.org/web/profile/mr-subhash-chandra-roy1',
'https://fbcci.org/web/profile/mr-tamal-kumar-ghosh1',
'https://fbcci.org/web/profile/mr-salahuddin-mohammad-babor',
'https://fbcci.org/web/profile/mr-mohammad-zahidul-islam',
'https://fbcci.org/web/profile/mr-md-shahabuddin1',
'https://fbcci.org/web/profile/mr-abdul-wahed%0A-%0A-%0A',
'https://fbcci.org/web/profile/mr-md-khairul-islam',
'https://fbcci.org/web/profile/mr-md-mofiz-uddin',
'https://fbcci.org/web/profile/md-harun-or-rashid',
'https://fbcci.org/web/profile/mr-md-abdul-awal',
'https://fbcci.org/web/profile/mr-md-monirul-islam',
'https://fbcci.org/web/profile/mr-mahbubul-alam',
'https://fbcci.org/web/profile/mr-tarafder-md-ruhul-amin',
'https://fbcci.org/web/profile/mr-syed-mohammed-tanvir',
'https://fbcci.org/web/profile/mr-mohammed-nurunnewaz',
'https://fbcci.org/web/profile/mr-omar-hazzaz',
'https://fbcci.org/web/profile/mr-akm-akther-hossain',
'https://fbcci.org/web/profile/mr-khalilur-rahman',
'https://fbcci.org/web/profile/mr-md-showkat-ali-chowdhury',
'https://fbcci.org/web/profile/mr-a-m-mahbub-chowdhury-',
'https://fbcci.org/web/profile/mr-m-a-malek-',
'https://fbcci.org/web/profile/mr-mohammed-abdus-salam',
'https://fbcci.org/web/profile/mr-mohammed-wahid-rihan-iftakhar-mahmud',
'https://fbcci.org/web/profile/ms-monwara-hakim-ali',
'https://fbcci.org/web/profile/dr-munal-mahbub',
'https://fbcci.org/web/profile/most-rozina-akter',
'https://fbcci.org/web/profile/ms-rokshana-akther-chowdhury',
'https://fbcci.org/web/profile/ms-ayesha-farha-chowdhury',
'https://fbcci.org/web/profile/ms-shanewaz-ayesha-akhtar-jahan',
'https://fbcci.org/web/profile/mr-md-yakub-hossen-malik1',
'https://fbcci.org/web/profile/mr-dilip-kumar-agarwala',
'https://fbcci.org/web/profile/mr-md-harun-ar-rashid',
'https://fbcci.org/web/profile/mr-md-tazul-islam1',
'https://fbcci.org/web/profile/mr-md-kamrul-islam',
'https://fbcci.org/web/profile/mr-suresh-kumar-agorwala',
'https://fbcci.org/web/profile/dr-azam-khan-noman',
'https://fbcci.org/web/profile/mr-md-iftekhar-khan',
'https://fbcci.org/web/profile/mr-niser-uddin-ahmed',
'https://fbcci.org/web/profile/mr-md-taimur-ahmed-bhuyan',
]


def create_directory_and_file(directory):
    dir_name, file_name = os.path.split(directory)    
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)
        print(f"Directory '{dir_name}' created.")
            
    file_path = os.path.join(dir_name, file_name)
    if not os.path.exists(file_path):
        with open(file_path, 'w') as file:
            file.write("This is a new file.")
        print(f"File '{file_path}' created.")
    else:
        print(f"File '{file_path}' already exists.")



def print_urls(start, end, file_name,driver):
    file_name = './fbcci/'+file_name
    create_directory_and_file(file_name)

    for url in urls[start:end]:
        print(url)        
        driver.get(url)
        text = driver.find_element(By.TAG_NAME, 'body').text
        save_text_to_text_file(text, file_name)        




# Function to divide the array into n threads and print URLs
def print_urls_in_threads(n):
    thread_list = []
    urls_per_thread = len(urls) // n  # dividing number of URLs among n threads

    for i in range(n):
        start = i * urls_per_thread
        end = (i + 1) * urls_per_thread if i < n - 1 else len(urls)
        driver = webdriver.Firefox();
        file_name = f'urls_thread_{i}.txt'  # Generating file name
        thread = threading.Thread(target=print_urls, args=(start, end, file_name,driver))
        thread_list.append(thread)
        thread.start()

    for thread in thread_list:
        thread.join()

# Example usage with 5 threads
print_urls_in_threads(7)

